### ISSUE TITLE
Styl pouze pro studenty

### ISSUE THREAD

**Issue by KuchynkaMarek** [martykan/vut-wis-style#1]
Styl ovlivňuje i úvodní stránku a zaměstnanecký wis. Úvodní stránka (https://wis.fit.vutbr.cz/FIT) by se stylovat neměla a stejně tak zaměstnanecký wis (https://wis.fit.vutbr.cz/FIT/db).

**Řešení:**
8. řádek
`@-moz-document url-prefix("https://wis.fit.vutbr.cz")` 
nahradit za
`@-moz-document url-prefix("https://wis.fit.vutbr.cz/FIT/st")`

**Comment by martykan** [comment]
Díky, upraveno
